# Generated by Django 5.1.5 on 2025-02-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("Phone", "Phone"),
                            ("SocialMedia", "Social Media"),
                            ("YouTube", "YouTube"),
                        ],
                        help_text="Type of contact detail.",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Phone number, social media link, or YouTube link.",
                        max_length=255,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional label (e.g., Home, Work, Facebook, etc.).",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
