# Generated by Django 5.1.7 on 2025-04-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactDetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='contact_type',
            field=models.CharField(choices=[('Phone', 'Phone'), ('SocialMedia', 'Social Media'), ('YouTube', 'YouTube'), ('Instagram', 'Instagram'), ('facebook', 'Facebook')], help_text='Type of contact detail.', max_length=20),
        ),
    ]
