# Generated by Django 5.1.7 on 2025-04-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
        ('media', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='image_alt',
        ),
        migrations.RemoveField(
            model_name='banners',
            name='image',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='logo',
        ),
        migrations.AlterField(
            model_name='seo',
            name='scripts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banners',
            name='image',
            field=models.ManyToManyField(related_name='image', to='media.media'),
        ),
        migrations.AddField(
            model_name='seo',
            name='logo',
            field=models.ManyToManyField(related_name='imagess', to='media.media'),
        ),
    ]
