# Generated by Django 5.2 on 2025-04-21 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_instructor"),
        ("homepage", "0002_remove_banners_image_alt_remove_banners_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(blank=True, max_length=5000, null=True)),
                ("answer", models.CharField(blank=True, max_length=5000, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for homepage",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="courses.course",
                    ),
                ),
            ],
        ),
    ]
