# Generated by Django 5.2 on 2025-04-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0004_facility"),
    ]

    operations = [
        migrations.CreateModel(
            name="home_page_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
    ]
