# Generated by Django 5.2 on 2025-04-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_instructor"),
        ("homepage", "0006_home_page_data_canonical_home_page_data_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnquiryForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=50)),
                ("message", models.CharField(max_length=250)),
                ("states", models.CharField(blank=True, max_length=200)),
                ("cities", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.ManyToManyField(
                        blank=True, related_name="courses", to="courses.course"
                    ),
                ),
            ],
        ),
    ]
