# Generated by Django 5.2 on 2025-04-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0007_enquiryform"),
    ]

    operations = [
        migrations.AddField(
            model_name="seo",
            name="url",
            field=models.CharField(
                blank=True, help_text="url", max_length=500, null=True
            ),
        ),
        migrations.RemoveField(model_name="seo", name="logo",),
        migrations.AddField(
            model_name="seo", name="logo", field=models.URLField(blank=True, null=True),
        ),
    ]
