# Generated by Django 5.1.7 on 2025-04-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allstudents', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='student',
            field=models.ManyToManyField(related_name='reviews', to='allstudents.student'),
        ),
    ]
