# Generated by Django 5.1.7 on 2025-04-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('reviews', '0002_review_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ManyToManyField(related_name='reviews', to='courses.course'),
        ),
    ]
