# Generated by Django 5.1.7 on 2025-04-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0002_rename_name_city_city_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5550)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slider_images', models.JSONField(blank=True, default=list)),
                ('meta_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('student_list', models.JSONField(blank=True, default=list, null=True)),
                ('city', models.ManyToManyField(related_name='city', to='location.city')),
                ('locality', models.ManyToManyField(related_name='locality', to='location.locality')),
                ('state', models.ManyToManyField(related_name='state', to='location.state')),
            ],
        ),
    ]
