# Generated by Django 5.1.7 on 2025-04-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allstudents', '0003_alter_student_courses'),
        ('courses', '0003_alter_course_studentids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student_list',
        ),
        migrations.AddField(
            model_name='course',
            name='student_list',
            field=models.ManyToManyField(related_name='stidentlists', to='allstudents.student'),
        ),
    ]
