# Generated by Django 5.1.7 on 2025-04-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allstudents", "0004_alter_student_homepage_alter_student_name"),
        ("courses", "0004_remove_course_student_list_course_student_list"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="studentids",),
        migrations.AddField(
            model_name="course",
            name="created_by",
            field=models.CharField(blank=True, max_length=5550, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="student_list",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="stidentlists",
                to="allstudents.student",
            ),
        ),
    ]
