# Generated by Django 5.1.7 on 2025-04-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_remove_course_studentids_course_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.CharField(blank=True, max_length=5550, null=True),
        ),
    ]
