# Generated by Django 5.1.7 on 2025-04-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.CharField(
                blank=True, default="3months", max_length=550, null=True
            ),
        ),
    ]
