# Generated by Django 5.1.7 on 2025-04-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_course_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=200)),
                ("experience", models.PositiveIntegerField()),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="instructor_profiles/"
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="instructors",
                        to="courses.course",
                    ),
                ),
            ],
        ),
    ]
