# Generated by Django 5.1.7 on 2025-04-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('location', '0002_rename_name_city_city_name_and_more'),
        ('media', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('homepage', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_descriptions', models.CharField(blank=True, max_length=1000, null=True)),
                ('meta_keyWords', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=1500, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=500, null=True)),
                ('review', models.CharField(blank=True, max_length=500, null=True)),
                ('cities', models.ManyToManyField(blank=True, null=True, related_name='allstudents', to='location.city')),
                ('courses', models.ManyToManyField(blank=True, null=True, related_name='allstudents', to='courses.course')),
                ('image', models.ManyToManyField(blank=True, null=True, related_name='allstudents', to='media.media')),
                ('localities', models.ManyToManyField(blank=True, null=True, related_name='allstudents', to='location.locality')),
                ('states', models.ManyToManyField(blank=True, null=True, related_name='allstudents', to='location.state')),
            ],
        ),
    ]
