# Generated by Django 5.1.7 on 2025-04-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allstudents', '0001_initial'),
        ('media', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='allstudentsmedia', to='media.media'),
        ),
    ]
