# Generated by Django 5.1.7 on 2025-04-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allstudents', '0003_alter_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='homepage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
